"""The 19 beats of "Essentially, We Did It", word for word from the production sheet.

Every line is invented parody dialogue, not a statement, quotation or admission by Ferran Soriano or Manchester City.

Each phrase is (tag, caption text). The tag is the performance cue from the sheet ([sigh], [laughs], [whispers],
[excited], [sad]); it is never spoken or captioned. Capitals mark the stressed words, as in the sheet. Where the
recording says something slightly different from the page, the caption follows the recording: "we are" instead of
"we're" in three lines (beats 12 and 17)."""

BEATS = [
 (1, [("sigh", "I want to share some information about the ongoing disciplinary process between Manchester City and the Premier League."),
      ("laughs", "Essentially, we DID it."),
      (None, "But I think people are being very negative about that.")]),
 (2, [(None, "A document has been published which is negative to our interests."),
      ("sigh", "Unfortunately, it is also quite ACCURATE."),
      ("laughs", "We had specifically asked for those two things not to happen together.")]),
 (3, [(None, "I want to explain what happens next, how we will defend the club, and why doing everything they accused us of doesn't necessarily mean we should face CONSEQUENCES."),
      (None, "We've checked with our lawyers."),
      ("whispers", "They're happy to discuss that for several more years.")]),
 (4, [("sigh", "The whole case is based on one accusation: that our owner's personal money was secretly put into the club through sponsors."),
      ("laughs", "YES."),
      (None, "But \"secretly\" makes it sound sinister."),
      ("whispers", "We simply didn't tell the people who would have STOPPED us.")]),
 (5, [(None, "And the money didn't come DIRECTLY from the owner."),
      (None, "It went through a sponsor first."),
      ("laughs", "Completely different pocket."),
      ("sigh", "I don't understand why everyone keeps bringing up the TROUSERS.")]),
 (6, [("excited", "We supplied IRREFUTABLE evidence."),
      (None, "Bank statements. Money transfers. Witnesses."),
      (None, "Everything necessary to demonstrate EXACTLY what we'd done."),
      ("sad", "We thought they would appreciate how organised we were.")]),
 (7, [(None, "Instead, they followed the money."),
      (None, "ALL the way."),
      (None, "Which, frankly, felt a bit obsessive.")]),
 (8, [(None, "Every other charge comes from that one simple arrangement."),
      (None, "People say \"one hundred and fifteen\" as though we sat down and broke one hundred and fifteen SEPARATE rules."),
      ("laughs", "We were much more efficient than that.")]),
 (9, [("sigh", "And these charges have been aggressively marketed and promoted."),
      (None, "Every newspaper. Every television channel."),
      ("sad", "We normally pay a fortune for that kind of coverage, and suddenly nobody wants their logo next to us.")]),
 (10, [(None, "After nearly two years, the commission has agreed with the Premier League."),
       (None, "Apparently, if you provide enough evidence that something happened, they decide it HAPPENED."),
       ("sad", "Nobody explained that part to us.")]),
 (11, [(None, "They have completely ignored the wider context."),
       ("excited", "The football was LOVELY."),
       (None, "You've seen the passing."),
       (None, "Surely that cancels out a few bank transfers.")]),
 (12, [("sigh", "Our lawyers will now appeal because the ruling contains serious errors of law, principle and fact."),
       (None, "The LAW was applied to us."),
       (None, "PRINCIPLES were expected of us."),
       (None, "And the FACTS have been made public."),
       (None, "You can see why we are concerned.")]),
 (13, [("excited", "Remember, we have been here before."),
       (None, "In 2020, we appealed to CAS and won."),
       (None, "We mention this whenever ANYTHING happens."),
       (None, "Parking ticket? CAS."),
       (None, "Late invoice? CAS."),
       (None, "My wife says I haven't emptied the dishwasher?"),
       ("laughs", "We've been CLEARED of this before.")]),
 (14, [("excited", "We will pursue every legal avenue available."),
       (None, "Our preference remains the avenue where we KEEP everything and everyone else stops fucking asking.")]),
 (15, [("sad", "We will also seek compensation from anyone damaging our reputation."),
       ("whispers", "Yes, our actions contributed."),
       ("sigh", "But people FINDING OUT has made it considerably worse.")]),
 (16, [("sigh", "I know this is a distraction. Please remain focused on our business and our extended City family."),
       ("laughs", "And remember: just because the money goes round several relatives before reaching you doesn't make it any less of a GIFT.")]),
 (17, [(None, "Please follow the usual procedure for enquiries."),
       (None, "If a supporter asks, say we are INNOCENT."),
       (None, "If a journalist asks, say we are APPEALING."),
       ("whispers", "If a sponsor asks, check whether it's actually the owner.")]),
 (18, [("excited", "Very soon, we will look back on this as another time we faced adversity and overcame it together."),
       ("whispers", "Admittedly, we CREATED the adversity."),
       ("excited", "But we also created the sponsorship revenue."),
       ("laughs", "You have to look at the POSITIVES.")]),
 (19, [(None, "Thank you."),
       (None, "And please remember: money cannot buy success."),
       ("whispers", "According to our lawyers, it merely arrives independently, through a commercial partner, shortly before success happens.")]),
]

# how a caption word is said, where the recording's words differ from the spelling
SAID = {"2020": ["twenty", "twenty"], "organised": ["organized"]}
