"""Rebuild library/INDEX.md (the browsable list of everything in the library) and check for loose ends.

    python3 tools/index_library.py            # rewrite library/INDEX.md
    python3 tools/index_library.py --check    # also list problems and exit 1 if there are any

Checked: every character has a character.yaml; every kit sheet is there, labelled and checked by eye; every file in
a character's reference/ folder is described in its character.yaml (and the other way round); every background,
prop, extra and reference scene on disk is in its index yaml (and the other way round); every character has a
voice folder."""
import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from studio.paths import AUDIO, BACKGROUNDS, CHARACTERS, EXTRAS, LIBRARY, PROPS, REFERENCE, VOICES  # noqa: E402

KIT_VIEWS = ("front", "three_quarter", "side", "hands")
SETTING_TITLES = {"stadiums": "Stadiums", "white-pele": "The White Pelé sets", "training-ground": "Training ground", "club": "Club interiors",
                  "tv-and-media": "TV and media", "home": "Home", "spa-and-pool": "Spa and pool",
                  "pub-and-restaurant": "Pub and restaurant", "nightlife": "Nightlife", "street": "Street",
                  "concert": "Concert (Manchester Arena)"}
problems = []


def load(path):
    return yaml.safe_load(Path(path).read_text()) or {}


def link(path, text=None):
    path = Path(path).relative_to(LIBRARY).as_posix()
    return f"[{text or Path(path).name}]({path})"


def kit_status(cdir, c):
    """('4/4 checked' | 'n/4 ...' | 'no kit', problems)"""
    have, unchecked = set(), []
    for outfit in c.get("outfits", {}):
        for view in KIT_VIEWS:
            png = cdir / "kit" / outfit / f"{view}.png"
            if not png.exists():
                continue
            have.add((outfit, view))
            yml = png.with_suffix(".yaml")
            if not yml.exists() or not load(yml).get("checked"):
                unchecked.append(f"{cdir.name}/{outfit}/{view}")
    if not have:
        return "no kit yet"
    outfits = len({o for o, _ in have})
    missing = [f"{cdir.name}/{o}/{v}" for o in c["outfits"] for v in KIT_VIEWS if (o, v) not in have and any(x[0] == o for x in have)]
    problems.extend(f"kit sheet not labelled or not checked: {u}" for u in unchecked)
    problems.extend(f"kit sheet missing: {m}" for m in missing)
    done = len(have) - len(unchecked)
    return f"{done}/{outfits * len(KIT_VIEWS)} sheets checked"


def characters():
    rows = []
    for yml in sorted(CHARACTERS.glob("*/character.yaml")):
        cdir, c = yml.parent, load(yml)
        ref = cdir / "reference"
        files = {p.name for p in ref.iterdir() if p.suffix.lower() in (".png", ".jpg", ".jpeg")} if ref.exists() else set()
        described = set(c.get("reference", {}))
        problems.extend(f"reference file not described in {cdir.name}/character.yaml: {f}" for f in sorted(files - described))
        problems.extend(f"{cdir.name}/character.yaml describes a missing reference file: {f}" for f in sorted(described - files))
        if not (VOICES / cdir.name).is_dir():
            problems.append(f"no voice folder for {cdir.name}: library/audio/voiceovers/{cdir.name}/")
        voices = [p for p in (VOICES / cdir.name).glob("**/*") if p.is_file() and p.name != ".gitkeep"]
        rows.append((cdir.name, c, kit_status(cdir, c), len(files), len(voices)))
    return rows


def check_index(index_path, root, label, pattern="*.png", skip=()):
    idx = load(index_path)
    on_disk = {p.relative_to(root).with_suffix("").as_posix() for p in root.rglob(pattern)
               if not any(s in p.parts for s in skip)}
    problems.extend(f"{label}: {i} is on disk but not in {Path(index_path).name}" for i in sorted(on_disk - set(idx)))
    problems.extend(f"{label}: {i} is in {Path(index_path).name} but missing on disk" for i in sorted(set(idx) - on_disk))
    return idx


def render():
    out = ["# Library index", "",
           "Generated by `python3 tools/index_library.py`: don't edit by hand. How the library is organised, and how to add",
           "to it, is in [README.md](README.md).", ""]

    chars = characters()
    out += ["## Characters", "",
            "Folder = id = the full name in kebab-case. Episodes refer to a character by id.", "",
            "| Character | id | Role | Outfits | Puppet kit | Reference sheets | Voice clips |",
            "|---|---|---|---|---|---|---|"]
    for cid, c, kit, nref, nvoice in chars:
        style = c.get("style")
        tag = " (stand-in, off-style)" if style == "provisional" else ""
        out.append(f"| {c['name']}{tag} | [`{cid}`](characters/{cid}/) | {c.get('role', '')} | "
                   f"{', '.join(c.get('outfits', {})) or '-'} | {kit} | {nref} | {nvoice} |")
    out += ["", "Puppet kit = the front, three-quarter, side and hands sheets, labelled part by part and checked by eye. "
            "\"no kit yet\" characters have only reference art. Reference sheets live in each character's `reference/` folder, described in its `character.yaml`.", ""]

    bg = check_index(BACKGROUNDS / "backgrounds.yaml", BACKGROUNDS, "backgrounds", skip=("source",))
    out += ["## Backgrounds", "",
            f"{len(bg)} empty sets, by setting. Landscape fits the 16:9 episodes as they are; **portrait** ones (941x1672) need a "
            "landscape version or a crop first. Full details in [backgrounds.yaml](backgrounds/backgrounds.yaml).", ""]
    for setting in SETTING_TITLES:
        items = {k: v for k, v in bg.items() if k.split("/")[0] == setting}
        if not items:
            continue
        out += [f"### {SETTING_TITLES[setting]}", "", "| id | Set | Shape |", "|---|---|---|"]
        for k, v in items.items():
            out.append(f"| [`{k}`](backgrounds/{k}.png) | {v['title']} | {v['orientation']} {v['size'][0]}x{v['size'][1]} |")
        out.append("")
    unknown = {k.split("/")[0] for k in bg} - set(SETTING_TITLES)
    problems.extend(f"backgrounds: setting folder not in the index generator's list: {s}" for s in sorted(unknown))

    props = check_index(PROPS / "props.yaml", PROPS, "props", skip=("source",))
    out += ["## Props", "", f"{len(props)} cut-out props (transparent PNG). Uncut sheets are in each set's `source/` folder.", "",
            "| id | Prop |", "|---|---|"]
    out += [f"| [`{k}`](props/{k}.png) | {v['title']} |" for k, v in props.items()]
    out.append("")

    extras = check_index(EXTRAS / "extras.yaml", EXTRAS, "extras")
    out += ["## Extras (background cast)", ""]
    out += [f"- [`{k}`](extras/{k}.png): {v['contains']}" for k, v in extras.items()]
    out.append("")

    scenes_root = REFERENCE / "party-scenes"
    scenes = check_index(scenes_root / "scenes.yaml", scenes_root, "reference scenes")
    groups = {}
    for k in scenes:
        groups.setdefault(k.split("/")[0], []).append(k)
    out += ["## Reference scenes", "",
            "Older finished 'Stick to Football' party artwork, kept for the look and the staging; not animation assets. "
            "See [scenes.yaml](reference/party-scenes/scenes.yaml).", ""]
    out += [f"- `{g}/`: {len(v)} pictures" for g, v in groups.items()]
    out.append("")

    AUDIO_EXT = (".wav", ".flac", ".ogg", ".mp3", ".m4a")
    sfx = [p for p in (AUDIO / "sfx").glob("**/*") if p.is_file() and p.suffix.lower() in AUDIO_EXT]
    music = [p for p in (AUDIO / "music").glob("**/*") if p.is_file() and p.name not in (".gitkeep", "CREDITS.md")]
    nvoice = sum(r[4] for r in chars)
    out += ["## Audio", "",
            f"Voice bank: {nvoice} clips in {len(chars)} character folders; sound effects: {len(sfx)}; music: {len(music)}. "
            "See [audio/README.md](audio/README.md) for what goes where.", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="print the problems found and exit 1 if there are any")
    a = ap.parse_args()
    text = render()
    stray = [p.name for p in LIBRARY.iterdir() if p.is_file() and p.name not in ("README.md", "INDEX.md")]
    problems.extend(f"loose file in library/: {n}" for n in stray)
    (LIBRARY / "INDEX.md").write_text(text)
    print(f"wrote {LIBRARY / 'INDEX.md'}")
    if problems:
        print(f"\n{len(problems)} problem(s):", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        if a.check:
            sys.exit(1)
    elif a.check:
        print("library is tidy")


if __name__ == "__main__":
    main()
